/**
 * Configurazione dati delle 5 wave della modalità Sfida.
 * Nessuna logica qui — solo valori. Per aggiungere o rimuovere wave
 * basta modificare questo array; il resto del sistema si adatta automaticamente.
 */
export const SFIDA_WAVES = [
  {
    id: 1,
    title: 'WAVE 1',
    objective: 'Distruggi il bersaglio, poi abbatti il nemico!',
    enemies: [{ role: 'aggressor', color: '#ff2222' }],
    allies: [],
    boss: null,
    hasTarget: true,
    killGoal: null,
    respawnMode: 'until_target', // bot rispawnano finché target non è distrutto
    playerLives: 3,
    playerStartBuilding: false,
    enemyStartBuilding: false,
    friendlyFire: false,
  },
  {
    id: 2,
    title: 'WAVE 2',
    objective: 'Proteggi la tua base — abbatti entrambi i nemici!',
    enemies: [
      { role: 'aggressor', color: '#ff2222' },
      { role: 'strategist', color: '#ff6600' },
    ],
    allies: [],
    boss: null,
    hasTarget: false,
    killGoal: 2,
    respawnMode: 'never',
    playerStartBuilding: true,
    enemyStartBuilding: false,
    friendlyFire: false,
  },
  {
    id: 3,
    title: 'WAVE 3',
    objective: 'Raggiungi 10 abbattimenti insieme al tuo alleato!',
    enemies: [
      { role: 'aggressor', color: '#ff2222' },
      { role: 'aggressor', color: '#cc0000' },
      { role: 'strategist', color: '#880000' },
      { role: 'strategist', color: '#aa2200' },
    ],
    allies: [{ role: 'aggressor', color: '#00ff88', nickname: 'Wingman' }],
    boss: null,
    hasTarget: false,
    killGoal: 10,
    respawnMode: 'always',
    playerStartBuilding: false,
    enemyStartBuilding: false,
    friendlyFire: false,
  },
  {
    id: 4,
    title: 'WAVE 4',
    objective: 'Distruggi la base nemica e abbatti tutti e 6 i nemici!',
    enemies: [
      { role: 'aggressor', color: '#ff2222' },
      { role: 'aggressor', color: '#dd0000' },
      { role: 'strategist', color: '#990000' },
      { role: 'strategist', color: '#bb1100' },
      { role: 'strategist', color: '#cc2200' },
      { role: 'aggressor', color: '#ff3300' },
    ],
    allies: [
      { role: 'strategist', color: '#00ff88', nickname: 'Falcon' },
      { role: 'aggressor', color: '#00ccff', nickname: 'Storm' },
    ],
    boss: null,
    hasTarget: false,
    killGoal: 6,
    respawnMode: 'never',
    playerStartBuilding: false,
    enemyStartBuilding: true,
    friendlyFire: false,
  },
  {
    id: 5,
    title: 'WAVE 5 — BOSS',
    objective: 'Abbatti il Boss! Ha 5 vite.',
    enemies: [],
    allies: [],
    boss: { color: '#8800ff', nickname: 'NEMESIS', lives: 5, weaponLevel: 2 },
    hasTarget: false,
    killGoal: null,
    respawnMode: 'never',
    playerStartBuilding: false,
    enemyStartBuilding: false,
    friendlyFire: false,
  },
];
